#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const miniprogramRoot = path.join(__dirname, '..');
const envPath = path.join(miniprogramRoot, '.env');
const envExamplePath = path.join(miniprogramRoot, '.env.example');
const outputPath = path.join(miniprogramRoot, 'utils', 'env.js');

const defaults = {
  MINIPROGRAM_SERVER_ENV: 'test',
  MINIPROGRAM_TEST_BASE_URL: 'http://127.0.0.1:5100',
  MINIPROGRAM_PRODUCTION_BASE_URL: 'http://124.220.171.165:3000',
};

const envAliases = {
  test: 'test',
  testing: 'test',
  prod: 'production',
  production: 'production',
};

function parseEnv(raw) {
  return raw.split(/\r?\n/).reduce((env, line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return env;
    }

    const separatorIndex = trimmed.indexOf('=');
    if (separatorIndex === -1) {
      return env;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
    return env;
  }, {});
}

function readEnvFile() {
  const sourcePath = fs.existsSync(envPath) ? envPath : envExamplePath;
  if (!fs.existsSync(sourcePath)) {
    return {};
  }

  return parseEnv(fs.readFileSync(sourcePath, 'utf8'));
}

function normalizeActiveEnv(value) {
  const normalized = String(value || '').trim().toLowerCase();
  return envAliases[normalized] || null;
}

const env = {
  ...defaults,
  ...readEnvFile(),
};

const activeEnv = normalizeActiveEnv(env.MINIPROGRAM_SERVER_ENV);
if (!activeEnv) {
  throw new Error('MINIPROGRAM_SERVER_ENV must be test or production');
}

const servers = {
  test: env.MINIPROGRAM_TEST_BASE_URL,
  production: env.MINIPROGRAM_PRODUCTION_BASE_URL,
};

if (!servers.test || !servers.production) {
  throw new Error('MINIPROGRAM_TEST_BASE_URL and MINIPROGRAM_PRODUCTION_BASE_URL are required');
}

const output = `// Generated by miniprogram/scripts/sync-env.js from miniprogram/.env.
// Do not edit this file directly.

const ENV = ${JSON.stringify(activeEnv)};
const SERVERS = ${JSON.stringify(servers, null, 2)};
const BASE_URL = SERVERS[ENV];

module.exports = {
  ENV,
  SERVERS,
  BASE_URL,
};
`;

fs.writeFileSync(outputPath, output);
console.log(`Wrote ${path.relative(process.cwd(), outputPath)} (${activeEnv}: ${servers[activeEnv]})`);
