// Generated by miniprogram/scripts/sync-env.js from miniprogram/.env.
// Do not edit this file directly.

const ENV = "production";
const SERVERS = {
  "test": "http://192.168.0.22:5100",
  "production": "https://admin.sindyfish.cloud/api/"
};
const BASE_URL = SERVERS[ENV];

module.exports = {
  ENV,
  SERVERS,
  BASE_URL,
};
